# netlify.toml
# Configuration file for Netlify deployment

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  
  # Default build command
  command = "CI=false npm run build"

# Redirects for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to enhance security and caching
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'"
    
# Cache settings for static assets
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"